server:
  port: 8080

spring:
  application:
    name: pulse-backend
  datasource:
    url: jdbc:mysql://localhost:3306/pulse
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

pulse:
  jwt:
    secret: change-me-to-a-long-random-string-later
    expiration-ms: 86400000